/**
 * Vitest-only stub for SvelteKit's `$env/dynamic/private` virtual module.
 *
 * `$env/dynamic/private` is generated by `svelte-kit sync` and only exists
 * in the vite-driven build pipeline. Vitest doesn't run that pipeline, so
 * any test that transitively imports a server module (which `$lib/server/*`
 * frequently does) crashes at module-load time without this alias.
 *
 * The unit tests that hit this stub are the pure helpers in
 * `$lib/server/api-key.ts` (generateApiKey, extractPrefix, verifyToken).
 * They never call into the database, so `DATABASE_URL` is just a non-empty
 * placeholder used to pass `$lib/server/db/index.ts`'s startup check.
 * Integration-level coverage of database-touching code lives in `e2e/`.
 */
export const env = {
	DATABASE_URL: 'postgresql://vitest-stub@localhost:5432/vitest-stub'
} as Record<string, string | undefined>;
